name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.214.141.214
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd aws-cicd-demo
            git pull origin main
            npm install
            pm2 restart aws-cicd-demo
